import { v4 as uuid } from "uuid";
export const products = [
    {
        id: uuid(),
        title:"Acoustic Guitar",
        image :'https://raw.githubusercontent.com/shuklahimanshu81/Blossom-store-react-app/Dev/blossom-store/src/Assets/Drum.jpg',  
        price: "5000",
        categoryName: "Guitar",
      },
      {
        id: uuid(),
        title:"Acoustic Guitar",
        image :'https://raw.githubusercontent.com/shuklahimanshu81/Blossom-store-react-app/Dev/blossom-store/src/Assets/Drum.jpg',  
        price: "5000",
        categoryName: "Guitar",
      },
      {
        id: uuid(),
        title:"Acoustic Guitar",
        image :'https://raw.githubusercontent.com/shuklahimanshu81/Blossom-store-react-app/Dev/blossom-store/src/Assets/Drum.jpg',  
        price: "5000",
        categoryName: "Guitar",
      },
      {
        id: uuid(),
        title:"Acoustic Guitar",
        image :'https://raw.githubusercontent.com/shuklahimanshu81/Blossom-store-react-app/Dev/blossom-store/src/Assets/Drum.jpg',  
        price: "5000",
        categoryName: "Guitar",
      },
      {
        id: uuid(),
        title:"Acoustic Guitar",
        image :'https://raw.githubusercontent.com/shuklahimanshu81/Blossom-store-react-app/Dev/blossom-store/src/Assets/Drum.jpg',  
        price: "5000",
        categoryName: "Guitar",
      },
      {
        id: uuid(),
        title:"Acoustic Guitar",
        image :'https://raw.githubusercontent.com/shuklahimanshu81/Blossom-store-react-app/Dev/blossom-store/src/Assets/Drum.jpg',  
        price: "5000",
        categoryName: "Guitar",
      },
      {
        id: uuid(),
        title:"Acoustic Guitar",
        image :'https://raw.githubusercontent.com/shuklahimanshu81/Blossom-store-react-app/Dev/blossom-store/src/Assets/Drum.jpg',  
        price: "5000",
        categoryName: "Guitar",
      },
      {
        id: uuid(),
        title:"Acoustic Guitar",
        image :'https://raw.githubusercontent.com/shuklahimanshu81/Blossom-store-react-app/Dev/blossom-store/src/Assets/Drum.jpg',  
        price: "5000",
        categoryName: "Guitar",
      },
      {
        id: uuid(),
        title:"Acoustic Guitar",
        image :'https://raw.githubusercontent.com/shuklahimanshu81/Blossom-store-react-app/Dev/blossom-store/src/Assets/Drum.jpg',  
        price: "5000",
        categoryName: "Guitar",
      },
      {
        id: uuid(),
        title:"Acoustic Guitar",
        image :'https://raw.githubusercontent.com/shuklahimanshu81/Blossom-store-react-app/Dev/blossom-store/src/Assets/Drum.jpg',  
        price: "5000",
        categoryName: "Guitar",
      },
      {
        id: uuid(),
        title:"Acoustic Guitar",
        image :'https://raw.githubusercontent.com/shuklahimanshu81/Blossom-store-react-app/Dev/blossom-store/src/Assets/Drum.jpg',  
        price: "5000",
        categoryName: "Guitar",
      },
      {
        id: uuid(),
        title:"Acoustic Guitar",
        image :'https://raw.githubusercontent.com/shuklahimanshu81/Blossom-store-react-app/Dev/blossom-store/src/Assets/Drum.jpg',  
        price: "5000",
        categoryName: "Guitar",
      },
      {
        id: uuid(),
        title:"Acoustic Guitar",
        image :'https://raw.githubusercontent.com/shuklahimanshu81/Blossom-store-react-app/Dev/blossom-store/src/Assets/Drum.jpg',  
        price: "5000",
        categoryName: "Guitar",
      },
      {
        id: uuid(),
        title:"Acoustic Guitar",
        image :'https://raw.githubusercontent.com/shuklahimanshu81/Blossom-store-react-app/Dev/blossom-store/src/Assets/Drum.jpg',  
        price: "5000",
        categoryName: "Guitar",
      },
      {
        id: uuid(),
        title:"Acoustic Guitar",
        image :'https://raw.githubusercontent.com/shuklahimanshu81/Blossom-store-react-app/Dev/blossom-store/src/Assets/Drum.jpg',  
        price: "5000",
        categoryName: "Guitar",
      },
      {
        id: uuid(),
        title:"Acoustic Guitar",
        image :'https://raw.githubusercontent.com/shuklahimanshu81/Blossom-store-react-app/Dev/blossom-store/src/Assets/Drum.jpg',  
        price: "5000",
        categoryName: "Guitar",
      }
];
